services:
  database:
    image: 'postgres:15.2'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_DB=library-management'
      - 'POSTGRES_PASSWORD=1234'